Repository terra-money/docs, pull requests merged in 2021-07, with the labels that each got.

#47 Fix typo
  docs/validator/faq.md
Labels: bug, documentation, good first issue

#51 Updated FCD swagger url
  docs/contracts/tutorial/setup.md
Labels: documentation, enhancement, good first issue

#50 Add CW20 tokens tutorial
  docs/.vuepress/config.js
  docs/contracts/tutorial/cw20.md
  package-lock.json
Labels: documentation, enhancement
